<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{cfaff396-02d6-4fc1-bf48-96a5a0da3de0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    TestSuite_ListOfTests : TestSuite_ListOfTests;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TestSuite_ListOfTests();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>