<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="T_ExampleInterfaceImplementation" Id="{67292391-722e-466e-b7ea-d2f4f341d700}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_ExampleInterfaceImplementation IMPLEMENTS I_ExampleInterface
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>