<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="T_UnitTestUnderTest" Id="{8cfb9b94-34ce-45da-9827-b7ad5a721e42}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_UnitTestUnderTest EXTENDS T_UnitTestBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>