<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TestSuite_ListOfTests" Id="{37b58022-812c-4470-9e56-2fe2415dcfd2}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'analysis' := '-33'} // inhibit unused variable warning
FUNCTION_BLOCK TestSuite_ListOfTests
VAR
    TestRunner                      : T_TestRunner;
    Test_GetTestHandlesEmptyList    : Test_GetTestHandlesEmptyList(TestRunner);
    Test_GetTestHandlesInvalidIndex : Test_GetTestHandlesInvalidIndex(TestRunner);
    Test_GetTestReturnsCorrectTest  : Test_GetTestReturnsCorrectTest(TestRunner);
    Test_IteratorReturnsTests       : Test_IteratorReturnsTests(TestRunner);
    Test_ListCountIncrements        : Test_ListCountIncrements(TestRunner);
    Test_ListClear                  : Test_ListClear(TestRunner);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TestRunner(TestSuiteName := 'TestSuite_ListOfTests');
]]></ST>
    </Implementation>
    <Method Name="AddTest" Id="{b78b7c35-615e-437f-9ccd-9a11a2a02d6c}">
      <Declaration><![CDATA[METHOD AddTest
VAR_INPUT
	UnitTest	: I_UnitTest;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[TestRunner.AddTest(UnitTest);]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_exit" Id="{781684c6-3f48-40c1-a987-34cc250a5b70}">
      <Declaration><![CDATA[METHOD FB_exit : BOOL
VAR_INPUT
	bInCopyCode : BOOL; // if TRUE, the exit method is called for exiting an instance that is copied afterwards (online change).
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[TestRunner.ClearTests();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>