<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PB_TestRunner" Id="{d6444dd0-a407-499b-af10-d5c873f52ae3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PB_TestRunner
VAR
TestFramework : TestFramework;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TestFramework();

//UnitTests.TestRunner();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>