<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TestSuite_ListOfTests" Id="{37b58022-812c-4470-9e56-2fe2415dcfd2}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'call_after_init'}
FUNCTION_BLOCK TestSuite_ListOfTests
VAR
    TestRunner : T_TestRunner();
							  
    Test_GetTestHandlesEmptyList    : Test_GetTestHandlesEmptyList;
    Test_GetTestHandlesInvalidIndex : Test_GetTestHandlesInvalidIndex;
    Test_GetTestReturnsCorrectTest  : Test_GetTestReturnsCorrectTest;
    Test_IteratorReturnsTests       : Test_IteratorReturnsTests;
    Test_ListCountIncrements        : Test_ListCountIncrements;
    Test_ListClear                  : Test_ListClear;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TestRunner.CyclicUpdate();
]]></ST>
    </Implementation>
    <Method Name="Init" Id="{74b12b47-a042-42a9-a29f-4a0c0bc94b78}">
      <Declaration><![CDATA[{attribute 'call_after_online_change_slot' := '100'}
{attribute 'call_after_init'}
METHOD Init : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[TestRunner.TestSuiteName := 'TestSuite_ListOfTests';
TestRunner.ClearTests();

TestRunner.AddTest(THIS^.Test_GetTestHandlesEmptyList);
TestRunner.AddTest(THIS^.Test_GetTestHandlesInvalidIndex);
TestRunner.AddTest(THIS^.Test_GetTestReturnsCorrectTest);
TestRunner.AddTest(THIS^.Test_IteratorReturnsTests);
TestRunner.AddTest(THIS^.Test_ListClear);
TestRunner.AddTest(THIS^.Test_ListCountIncrements);

TestRunner.Start();
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>